"""Replace old Kaggle authentic doc entries in manifest with new synthetic ones."""
import json
from pathlib import Path

BACKEND = Path(__file__).resolve().parent.parent
MANIFEST_PATH = BACKEND / "data" / "eval_manifest.json"

with open(MANIFEST_PATH, encoding="utf-8") as f:
    manifest = json.load(f)

# Remove old Kaggle authentic entries
old_count = sum(1 for s in manifest["samples"]
                if s["sample_type"] == "document_image" and s["ground_truth"] == "authentic")

manifest["samples"] = [s for s in manifest["samples"]
                       if not (s["sample_type"] == "document_image" and s["ground_truth"] == "authentic")]

# Add new synthetic authentic entries
synthetic_files = [
    "synthetic_court_summons_001.jpg",
    "synthetic_police_notice_001.jpg",
    "synthetic_rto_notice_001.jpg",
    "synthetic_income_tax_notice_001.jpg",
    "synthetic_municipal_notice_001.jpg",
    "synthetic_consumer_forum_001.jpg",
    "synthetic_labour_court_001.jpg",
    "synthetic_high_court_notice_001.jpg",
    "synthetic_customs_notice_001.jpg",
    "synthetic_ngt_notice_001.jpg",
    "synthetic_sebi_notice_001.jpg",
    "synthetic_lok_adalat_001.jpg",
    "synthetic_gram_nyayalaya_001.jpg",
    "synthetic_debt_recovery_001.jpg",
    "synthetic_passport_seva_001.jpg",
]

new_entries = []
for i, fname in enumerate(synthetic_files, 1):
    new_entries.append({
        "sample_id": f"doc_auth_syn_{i:03d}",
        "sample_type": "document_image",
        "ground_truth": "authentic",
        "file_path": f"documents/authentic/{fname}",
        "source_citation": "Synthetic authentic Indian legal document generated by Bharat Kavach (reportlab/PIL) — clean formatting, no manipulation artifacts",
        "tricky_negative": False,
        "applicable_components": ["VisionForensics"]
    })

manifest["samples"].extend(new_entries)
manifest["manifest_version"] = 4

with open(MANIFEST_PATH, "w", encoding="utf-8") as f:
    json.dump(manifest, f, indent=2, ensure_ascii=False)

from collections import Counter
by = Counter(f"{s['sample_type']}:{s['ground_truth']}" for s in manifest["samples"])
print(f"Replaced {old_count} old Kaggle authentic docs with {len(new_entries)} synthetic ones")
print(f"Manifest v4 — totals:")
for k, v in sorted(by.items()):
    print(f"  {k}: {v}")
print(f"Grand total: {len(manifest['samples'])}")
